### ISSUE TITLE
not compatible on java 1.6

### ISSUE THREAD

**Issue by febryAMZ** [sitemesh/sitemesh2#25]
If im running on jdk 1.6 class TextEncoder.encode(...) always call method get13Buffer()

   ....
   if (JDK14) {
      return get14Buffer(data, encoding);
    }
    return get13Buffer(data, encoding);
  ....

**Comment by hazendaz** [comment]
strange, works fine on java 17.  will look at code more once I get full maven build working at https://github.com/hazendaz/sitemesh2, will modernizer most of it keeping it the same as 2.4.x or unreleased 2.5.x, couldn't figure out 3.x migration path and that is dead too so keeping this alive for psi probe so it can move to jakartaEE.  see https://github.com/hazendaz/sitemesh2

**Comment by hazendaz** [comment]
resolved on my fork by removing java 1.3 and before support.
