### ISSUE TITLE
Sitemesh 2.5 hasn't been published on Maven Central

### ISSUE THREAD

**Issue by rponte** [sitemesh/sitemesh2#27]
Hi guys,

Why hasn't Sitemesh **2.5** been published on Maven Central? I can't find it!

**Comment by hazendaz** [comment]
bringing project back to life, will release from here https://github.com/hazendaz/sitemesh2

**Comment by eschulma** [comment]
Now that this repo is itself back to life, it would be wonderful to get an official release on Maven Central. (I was one of the many that forked this repo, but would be happy to come back here.) I see there is a snapshot release elsewhere but I am wary of deploying that to production.

**Comment by codeconsole** [comment]
[Maven Central](https://repo.maven.apache.org/maven2/opensymphony/sitemesh/2.5.0/)
