### ISSUE TITLE
Might want to redirect people to SiteMesh's new home

### ISSUE THREAD

**Issue by JetForMe** [sitemesh/sitemesh2#28]
It's now at http://wiki.sitemesh.org/wiki/display/sitemesh/Home

**Comment by hazendaz** [comment]
new home is moving https://github.com/hazendaz/sitemesh2, not bothering here due to 10+ year old defunct state and immediate needs for psi-probe to get to jakartaEE as soon as possible.

**Comment by JetForMe** [comment]
Well, back in 2014 it might've been helpful.

**Comment by hazendaz** [comment]
true :)
