### ISSUE TITLE
sitemesh-2.4.2 can be compatible on jdk1.8?

### ISSUE THREAD

**Issue by beijingtangtang** [sitemesh/sitemesh2#38]
Jdk upgrade to 1.8, but NullPointerException occurs when jump to jsp page. 
Can you tell me sitemesh-2.4.2 can be compatible on java 1.8?

**Comment by hazendaz** [comment]
yes its compatible with java 8.  I use it in psi probe project on github and its being used through java 17 in production usage.  I'm taking over ownership on this here https://github.com/hazendaz/sitemesh2 for purposes of psi-probe in order to get it migrated to jakartaEE.
