### ISSUE TITLE
2.6.0 - create xml,  tlds for Jakarta EE 10

### ISSUE THREAD

**Issue by codeconsole** [sitemesh/sitemesh2#44]
https://github.com/sitemesh/sitemesh2/tree/2.6.x/src/etc/tld
https://github.com/sitemesh/sitemesh2/blob/2.6.x/src/etc/blank/WEB-INF/web.xml

**Comment by codeconsole** [comment]
@rainboyan, you updated the [1.1](https://github.com/sitemesh/sitemesh2/blob/2.6.x/src/etc/tld/sitemesh-page.tld) tag library instead of creating a [new folder like was done for 1.2](https://github.com/sitemesh/sitemesh2/tree/2.6.x/src/etc/tld/jsp1.2)

I am not against that, but we should probably remove the 1.2 folder then.   Have you confirmed the tlds are bundled in the jar?

**Comment by rainboyan** [comment]
@codeconsole I can confirm that the tlds will be included in the jar.
It's fine to remove the old versions. I will do it later.

**Comment by rainboyan** [comment]
@codeconsole Done. Anything else?

**Comment by codeconsole** [comment]
@rainboyan why did the publish plugin fail going from 2.0.0-rc-1 to 2.0.0?

https://github.com/sitemesh/sitemesh2/pull/43

**Comment by rainboyan** [comment]
I closed it because the two commits both changed the version of project.

It is time to release it now?

**Comment by codeconsole** [comment]
@rainboyan For some reason the publishing stopped working and I am not sure why.

```
* What went wrong:
Execution failed for task ':publishMavenJavaPublicationToSonatypeRepository'.
> Failed to publish publication 'mavenJava' to repository 'sonatype'
   > Could not PUT 'https://s01.oss.sonatype.org/content/repositories/snapshots/opensymphony/sitemesh/2.7.0-SNAPSHOT/sitemesh-2.7.0-20240701.062031-2.jar'. Received status code 401 from server: Content access is protected by token
```

**Comment by rainboyan** [comment]
@codeconsole Use generated token instead of the password 

https://central.sonatype.org/faq/401-error/#answer

https://central.sonatype.org/publish/generate-token/

**Comment by codeconsole** [comment]
@rainboyan can you run the latest snapshot 2.6.0-SNAPSHOT jar against Grace and verify it is good to release?

**Comment by rainboyan** [comment]
@codeconsole I just checked the snapshot version and it works well, it's good to release now.

**Comment by codeconsole** [comment]
2.6.0 has been released to Maven Central
