### ISSUE TITLE
Migrate java.net mailing list and Jive forums to Google Groups

### ISSUE THREAD

**Issue by sitemesh** [sitemesh/sitemesh2#5]
Old: https://sitemesh.dev.java.net/servlets/SummarizeList?listName=users
New: http://groups.google.com/group/sitemesh2-users

Old: https://sitemesh.dev.java.net/servlets/SummarizeList?listName=dev
New: http://groups.google.com/group/sitemesh-team
- Resubscribe all users on old list.
- Bonus: Determine if there's a way to import history. If so, kill Jive forums, otherwise leave it in place but set to read only and point to Group.
- Delete old list and update references.

**Comment by hazendaz** [comment]
no plan to restore this type of support
