### ISSUE TITLE
Move SiteMesh2 website to www.sitemesh.org/sitemesh2

### ISSUE THREAD

**Issue by sitemesh** [sitemesh/sitemesh2#6]
Currently it's running on the creaky old hard to access opensymphony.com server. Merge it with the www.sitemesh.org website that runs on AppEngine.

Old: http://www.opensymphony.com/sitemesh
New: http://www.sitemesh.org/sitemesh2
- It's probably easier to just copy the content and build into a new site structure, then to pull across the existing infrastructure.
- Setup permanent redirects on the old site to the new location.
- Ensure relevant links are updated.

Source for www.sitemesh.org: http://github.com/sitemesh/sitemesh

**Comment by hazendaz** [comment]
no need, site will be on github pages after https://github.com/hazendaz/sitemesh2 is released.
