### ISSUE TITLE
Clean out all open issues

### ISSUE THREAD

**Issue by sitemesh** [sitemesh/sitemesh2#8]
Read through all issues in http://jira.opensymphony.com/browse/SIM

Seeing as SM2 is being put into essential-bugfixes-only maintenance mode, many of these can be purged.
- If it's critical, move it here.
- If it's releated to SM3, move to SM3 github project.
- If it's older than a year, bin it.
- Delete Jira project and update links.

**Comment by hazendaz** [comment]
opensymphony doesn't exist.
